import { ComplianceRule, ComplianceConfig } from './types';

/**
 * 10 Mandatory Amazon Associates Program Compliance Rules
 * Based on Amazon Associates Program Operating Agreement & Policies (2026 Edition)
 */
export const AMAZON_COMPLIANCE_RULES: ComplianceRule[] = [
  {
    id: 'AMZ-RULE-01',
    ruleNumber: 1,
    title: 'Never Buy Through Your Own Affiliate Link',
    category: 'self_purchase',
    severity: 'warning',
    description: 'Do not purchase products for personal use, family members, friends, or colleagues through your own affiliate tracking links.',
    rationale: 'Amazon Associates strictly prohibits self-referrals and family purchases. Violations lead to immediate commission forfeiture and account termination.',
    remediation: 'Never click your own affiliate links when purchasing from Amazon. Use a clean browser profile without affiliate tags for personal shopping.',
    amazonPolicyRef: 'Associates Program Policies § 3 (Referral Requirements - Prohibition on Self-Purchases)',
    isConfigurable: false,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-02',
    ruleNumber: 2,
    title: 'Provide Value & Editorial Context Before Affiliate CTAs',
    category: 'pre_cta_value',
    severity: 'medium',
    description: 'Do not use raw/direct affiliate links as general traffic destinations or spam redirects without substantive editorial content.',
    rationale: 'Amazon requires traffic to come from bona fide editorial content, curated reviews, or comparison articles rather than direct click redirection spam.',
    remediation: 'Ensure affiliate buttons are placed within rich product reviews, comparisons, or buying guides with pros/cons and testing context.',
    amazonPolicyRef: 'Associates Program Participation Requirements § 1 (Content Standards)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-03',
    ruleNumber: 3,
    title: 'Approved Product Image Sources Only',
    category: 'image_usage',
    severity: 'critical',
    description: 'Do not download, scrape, and re-host Amazon product photos on private servers without official PA-API licensing or authorized CDN delivery.',
    rationale: 'Amazon owns or licenses proprietary product imagery. Unauthorized hosting violates copyright and Amazon Associates image policies.',
    remediation: 'Use official Amazon PA-API CDN URLs (e.g., m.media-amazon.com, images-na.ssl-images-amazon.com) or licensed editorial photography.',
    amazonPolicyRef: 'Associates Program Policies § 4 (Product Advertising API / Licensed Materials)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-04',
    ruleNumber: 4,
    title: 'Approved Pricing Methods & Live Disclaimers',
    category: 'pricing_disclaimer',
    severity: 'high',
    description: 'Do not display static Amazon product prices without clearly indicating that prices are subject to change and noting the date/time of capture.',
    rationale: 'Amazon prices fluctuate dynamically. Stale static prices mislead consumers unless accompanied by a mandatory real-time pricing disclaimer.',
    remediation: 'Display the disclaimer: "Product prices and availability are accurate as of the date/time indicated and are subject to change. Any price displayed on Amazon at the time of purchase will apply."',
    amazonPolicyRef: 'Associates Program Policies § 6 (Price and Availability Messaging)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-05',
    ruleNumber: 5,
    title: 'Account Activity & 180-Day Sales Health',
    category: 'account_health',
    severity: 'medium',
    description: 'Maintain regular qualifying referral activity. New Amazon Associates accounts must generate at least 3 qualifying sales within 180 days.',
    rationale: 'Inactive accounts or accounts failing to achieve 3 sales within 180 days are automatically rejected/closed by Amazon.',
    remediation: 'Monitor first-party click velocity and ensure active traffic is directed across featured buyer guides and high-conversion editorial pages.',
    amazonPolicyRef: 'Associates Program Operating Agreement § 2 (Application & Initial Sales Window)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-06',
    ruleNumber: 6,
    title: 'Mandatory Amazon Associates Program Disclosure',
    category: 'disclosure',
    severity: 'critical',
    description: 'Clearly and prominently display the mandatory Amazon Associates disclosure on all pages, articles, and reviews featuring affiliate links.',
    rationale: 'Both Amazon Associates Program Operating Agreement and FTC Guidelines legally mandate conspicuous affiliate disclosure.',
    remediation: 'Include the required statement: "As an Amazon Associate I earn from qualifying purchases" in the footer, header disclosure bar, and all review articles.',
    amazonPolicyRef: 'Associates Program Operating Agreement § 5 (Identifying Yourself as an Associate)',
    isConfigurable: false,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-07',
    ruleNumber: 7,
    title: 'No Prohibited URL Shorteners or Cloaking',
    category: 'url_cloaking',
    severity: 'critical',
    description: 'Do not use link-shortening services (e.g., bit.ly, tinyurl, ow.ly, t.co) to obscure or disguise Amazon affiliate destination URLs.',
    rationale: 'Amazon forbids cloaking affiliate links with generic third-party shorteners because consumers must know they are being directed to Amazon.',
    remediation: 'Use transparent internal routing (e.g. /go/[slug]) that redirects directly to official Amazon storefront domains, or use Amazon amzn.to shortlinks.',
    amazonPolicyRef: 'Associates Program Policies § 3 (Link Formatting - Prohibition on Obscuring Links)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-08',
    ruleNumber: 8,
    title: 'Zero Amazon Logo Graphics & Approved Text-Only CTAs',
    category: 'trademark_logo',
    severity: 'high',
    description: 'Never use Amazon logo assets, SVGs, icons, smile graphics, or logo-like badges anywhere on the site or in CTAs. All affiliate buttons must strictly use professional text-only CTAs.',
    rationale: 'Amazon trademark guidelines prohibit modifying official marks, creating custom logo buttons, or implying official Amazon store branding.',
    remediation: 'Use clean text-only CTAs such as "View on Amazon", "Check Price on Amazon", or "Buy on Amazon". Remove all Amazon logo SVGs, icons, and graphic assets.',
    amazonPolicyRef: 'Associates Program Trademark Guidelines § 1 (Approved Use of Marks)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-09',
    ruleNumber: 9,
    title: 'No False Endorsement Claims or Trademark Misuse',
    category: 'endorsement_claims',
    severity: 'critical',
    description: 'Do not claim or imply that Amazon endorses, sponsors, certifies, or partners with your website, reviews, or selections.',
    rationale: 'Associates are independent third parties. Claiming to be an "Official Amazon Partner" or "Amazon Certified Reviewer" is grounds for termination.',
    remediation: 'Remove any phrases claiming official partnership, endorsement, or Amazon warranty guarantee. State independence clearly.',
    amazonPolicyRef: 'Associates Program Operating Agreement § 4 (Relationship of Parties)',
    isConfigurable: true,
    enabled: true,
  },
  {
    id: 'AMZ-RULE-10',
    ruleNumber: 10,
    title: 'Regional Associate Tag Integrity & Account Structure',
    category: 'marketplace_tags',
    severity: 'high',
    description: 'Ensure regional affiliate tags correspond to the correct Amazon international marketplace and avoid duplicate conflicting account IDs.',
    rationale: 'Amazon operates separate Associates programs for each locale (US, UK, DE, CA, etc.). Using a US tag on amazon.co.uk loses commissions and causes tracking errors.',
    remediation: 'Map appropriate regional store tags (e.g. bestbuycart-20 for US, bestbuycartuk-21 for UK, bestbuycartde-21 for DE) and verify marketplace domains.',
    amazonPolicyRef: 'Associates Program Operating Agreement § 1 (International Marketplaces)',
    isConfigurable: true,
    enabled: true,
  },
];

/**
 * Default Compliance Configuration
 */
export const DEFAULT_COMPLIANCE_CONFIG: ComplianceConfig = {
  enabled: true,
  block_on_critical: true,
  block_on_high: true,
  sound_alert_enabled: true,
  require_timestamped_prices: true,
  require_footer_disclosure: true,
  require_article_disclosure: true,
  forbidden_trademark_phrases: [
    'amazon official partner',
    'official amazon partner',
    'official amazon store',
    'official amazon',
    'amazon certified',
    'amazon certified store',
    'certified by amazon',
    'endorsed by amazon',
    'amazon endorsed',
    'sponsored by amazon',
    'amazon authorized agent',
    'amazon official reviewer',
    'amazon representative',
    'official amazon representative',
    'amazon choice',
    "amazon's choice",
    'amazon verified',
    'amazon verified badge',
    'amazon prime exclusive',
    'prime member exclusive',
    'prime exclusive deal',
    'amazon exclusive deal',
    'amazon best seller',
    'amazon prime guarantee',
    'prime guaranteed by buy best cart',
    'amazon warranty guarantee',
    'amazon storefront buy best cart',
    'amazon affiliate guarantee',
    'amazon choice award',
    "amazon editor's choice",
    'official amazon discount',
  ],
  disallowed_url_domains: [
    'bit.ly',
    'bitly.com',
    'tinyurl.com',
    'short.io',
    'ow.ly',
    't.co',
    'goo.gl',
    'is.gd',
    'buff.ly',
    'adf.ly',
    'shorte.st',
    'cutt.ly',
    'rebrand.ly',
    'linktr.ee',
    'snip.ly',
    'trib.al',
    'ift.tt',
    'bl.ink',
    'soo.gd',
    'tiny.cc',
    'shorturl.at',
    's.id',
    'v.gd',
    'qr.ae',
    'clck.ru',
    'hyperurl.co',
    'smarturl.it',
    'chilp.it',
    'bc.vc',
    'u.to',
    'cutt.us',
    'lnkd.in',
    'db.tt',
    'cur.lv',
    'shortcm.li',
    'rb.gy',
    'dub.sh',
    'tiny.one',
    'short.gy',
    't.ly',
    'cleanuri.com',
    'shortlink.to',
    'surl.li',
  ],
  approved_image_hosts: [
    'm.media-amazon.com',
    'images-na.ssl-images-amazon.com',
    'images-amazon.com',
    'amazon.com',
    'images.unsplash.com',
    'buybestcart.shop',
    'localhost',
  ],
  approved_cta_phrases: [
    'buy on amazon',
    'view on amazon',
    'check price on amazon',
    'see on amazon',
    'shop on amazon',
    'check amazon price',
    'view deal on amazon',
    'claim amazon deal',
    'view details on amazon',
  ],
  mandatory_disclosure_phrase:
    'As an Amazon Associate, Buy Best Cart earns from qualifying purchases. Product prices and availability are accurate as of the date/time indicated and are subject to change.',
  pricing_disclaimer_template:
    'Prices, ratings, and availability are subject to change without notice on Amazon. Verify final pricing on the merchant storefront prior to purchase.',
  rules_toggle: {
    'AMZ-RULE-01': true,
    'AMZ-RULE-02': true,
    'AMZ-RULE-03': true,
    'AMZ-RULE-04': true,
    'AMZ-RULE-05': true,
    'AMZ-RULE-06': true,
    'AMZ-RULE-07': true,
    'AMZ-RULE-08': true,
    'AMZ-RULE-09': true,
    'AMZ-RULE-10': true,
  },
};
